@host = http://localhost:5001

GET  {{host}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NTIxNWEyZS1hZWIyLTQ3MTAtYjRkYS0wYzQ3OTY1ZTkzODkiLCJnaXZlbl9uYW1lIjoiQXJ0c2VtIiwiZmFtaWx5X25hbWUiOiJNaXJvbmF1IiwianRpIjoiMzhiYzhkMjItMzk0Ny00NmE5LTkzMjEtYzlhMjljNTdkNTg4IiwiZXhwIjoxNzI5MzAxOTc4LCJpc3MiOiJJbm5vX1Nob3AuSWRlbnRpdHlTZXJ2aWNlIiwiYXVkIjoiSW5ub19TaG9wLklkZW50aXR5U2VydmljZSJ9.kIUHrRv0ZhCo31lI-N_ljRYheU_GaPXbVl0920eLdfM