@host = http://localhost:5001

GET {{host}}/users/getuser/artmironov@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1OTdjOWNhOS1iNjFlLTRmMzUtOGY4Ni00NjVmNmMwNjU0MWUiLCJnaXZlbl9uYW1lIjoiQXJ0c2VtIiwiZmFtaWx5X25hbWUiOiJNaXJvbmF1IiwianRpIjoiOGE5ZmUzNTAtMTI0Ni00YTlmLTgzZWItMWNlYjAxOGFmMGJjIiwiZXhwIjoxNzI5Mzc4MTE5LCJpc3MiOiJJbm5vX1Nob3AuSWRlbnRpdHlTZXJ2aWNlIiwiYXVkIjoiSW5ub19TaG9wLklkZW50aXR5U2VydmljZSJ9.K90OpP73_zJNSNJeeBhLxyhGxKMxeS-vMcbt--89FuU
