version: '3.8'

services:
  api:
    container_name: identity-service-api
    build:
      context: .
      dockerfile: Inno_Shop.IdentityService/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure

  catalog-api:
    container_name: catalog-service-api
    build:
      context: .
      dockerfile: Inno_Shop.CatalogService/Dockerfile
    ports:
      - "5003:5003"
    depends_on:
      - catalog-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure

  db:
    # container_name: identity-service-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: YourPassword123
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
  
  catalog-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: YourPassword123
      ACCEPT_EULA: Y
    ports:
      - "1434:1433"