@host = http://localhost:5282

DELETE {{host}}/products/delete/9D06E4BB-5E80-41D7-AFAD-D179083E5616
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYjA2Nzk0MS0yNGQ1LTQxYzItYTI2MC0wMzVmNTlkZjNmNzAiLCJnaXZlbl9uYW1lIjoiQXJ0c2VtbSIsImZhbWlseV9uYW1lIjoiTWlyb25hdXUiLCJqdGkiOiJmOGEyZDkzYS00N2QzLTRiN2QtYTczYy00ZmEwNmExYTNlZmIiLCJleHAiOjE3MzAwMDI3NTksImlzcyI6Iklubm9fU2hvcC5JZGVudGl0eVNlcnZpY2UiLCJhdWQiOiJJbm5vX1Nob3AuSWRlbnRpdHlTZXJ2aWNlIn0.c66B_Z3lW5PKHcai62iLNbSirhjaUvYB9FzA1hazefA