@host = http://localhost:5001

POST {{host}}/auth/register
Content-Type: application/json

{
	"firstName": "Artsem",
	"lastName": "Mironau",
	"email": "artmironov@gmail.com",
	"password": "A123456b$"
}

###

POST {{host}}/auth/register
Content-Type: application/json

{
	"firstName": "Astsem",
	"lastName": "Mironau",
	"email": "artmironov98@gmail.com",
	"password": "A123456b$"
}

###

POST {{host}}/auth/register
Content-Type: application/json

{
	"firstName": "Artsem",
	"lastName": "Mironau",
	"email": "artmironogmail.com",
	"password": "123212"
}