@host = http://localhost:5001

DELETE {{host}}/users/delete/3b067941-24d5-41c2-a260-035f59df3f70
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYjA2Nzk0MS0yNGQ1LTQxYzItYTI2MC0wMzVmNTlkZjNmNzAiLCJnaXZlbl9uYW1lIjoiQXJ0c2VtbSIsImZhbWlseV9uYW1lIjoiTWlyb25hdXUiLCJqdGkiOiJlYmNmNDJhZS03MjAyLTQ1YzEtYTc2Ni1lYTdiNzFiZWZlM2YiLCJleHAiOjE3MzA1MTQzNTksImlzcyI6Iklubm9fU2hvcC5JZGVudGl0eVNlcnZpY2UiLCJhdWQiOiJJbm5vX1Nob3AuSWRlbnRpdHlTZXJ2aWNlIn0.xLxzwrXVqygWGYIk-Uozx6caPW0rHU5KzhgaW7TVLWw